version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/movemaster
      - SPRING_DATASOURCE_USERNAME=movemaster
      - SPRING_DATASOURCE_PASSWORD=movemaster
      - SERVER_SSL_KEY_STORE=/certs/keystore.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=changeit
      - SERVER_SSL_KEY_STORE_TYPE=PKCS12
    ports:
      - "8444:8443"
    volumes:
      - ./backend/src/main/resources:/certs:ro
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=movemaster
      - POSTGRES_USER=movemaster
      - POSTGRES_PASSWORD=movemaster
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
